services:
  - type: web
    name: n8n-lamachine
    env: docker
    plan: free
    region: frankfurt
    numInstances: 1
    envVars:
      - key: PORT
        value: 5678
      - key: N8N_LOG_LEVEL
        value: info
      - key: GENERIC_TIMEZONE
        value: America/Port-au-Prince
      - key: TZ
        value: America/Port-au-Prince
      - key: N8N_DEFAULT_LOCALE
        value: fr
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
      - key: NODE_OPTIONS
        value: --max-old-space-size=512
